//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPLEINGREDIENTCHECKLIST.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.DishIngredientAssociations = new HashSet<DishIngredientAssociation>();
        }
    
        public int DishId { get; set; }
        public string UserId { get; set; }
        public int RecipeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual ICollection<DishIngredientAssociation> DishIngredientAssociations { get; set; }
    }
}
